voting/node/urls.py
from django.urls import path
from .views import *

app_name = 'node'

urlpatterns = [
    #path('validate/', BlindToValidate.as_view(), name = 'blind_to_validate'),
    path('login/', Login.as_view(), name = 'login'),
    #path('', Home.as_view(), name = 'home'),
    path('', AuthHome.as_view(), name = 'auth_home'),
    path('new_validations/', NewValidation.as_view(), name = 'new_validations'),
    path('sign-blinded/<hashed_blinded_secret>/', SignBlinded.as_view(), name = 'sign_blinded'),
    path('view-blockchain/', AuthHome.as_view(), name = 'view_blockchain'),
    
]

voting/poll/urls.py
from django.urls import path, include
from .views import *

app_name = 'poll'

urlpatterns = [
    path('new_poll/', CreatePoll.as_view(), name = "new_question"),
    path('add_option/', AddOption.as_view(), name = "add_option"),
    path('home/', PollHome.as_view(), name = "poll_home"),
    path('mine/', MineBlock.as_view(), name = 'mine'), 
    path('<poll_id>/', PollDetailView.as_view(), name = "poll_detail"),
    path('<poll_id>/end_poll/', EndPoll.as_view(), name = "end_poll"),  
]

voting/voting/urls.py
from django.contrib import admin
from django.urls import path, include
from node.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
    path('', Home.as_view(), name = 'home'),
    path('validate/', BlindToValidate.as_view(), name = 'blind_to_validate'),
    path('unblind-signed/', UnblindSigned.as_view(), name = 'unblind_signed'),
    path('verify/', Verify.as_view(), name = 'verify_login'),
    path('authority/', include('node.urls')),
]

"""path('', Home.as_view(), name = 'home'),
path('validate/', BlindToValidate.as_view(), name = 'blind_to_validate'),
path('unblind-signed/', UnblindSigned.as_view(), name = 'unblind_signed'),
path('verify/', Verify.as_view(), name = 'verify_login'),
path('authority/', include('node.urls')),"""

voting/templates/auth_home.html
{% extends 'base.html' %}

{% block body %}

<div class = "container" style = "padding-top: 3.5%;">    
    <div class = "text-center">
        <div class="card">
            <h3 class="card-header special-color white-text">Authority</h3>
            <div class="card-body">
                <h4 class="card-title">Get Started</h4>
                

                <a href = "{% url 'node:new_validations' %}"><button type="button" class="btn btn-primary btn-lg">New Validation Requests</button></a>
                <a href = "{% url 'poll:new_question' %}"><button type="button" class="btn btn-primary btn-lg">Create New Poll</button></a>
                <a href = "{% url 'poll:poll_home' %}"><button type="button" class="btn btn-primary btn-lg">Manage Polls</button></a>

                
            </div>
        </div>
    </div>
</div>

{% endblock %}

voting/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>votecrypt</title>

    {% load static %}

    <!-- Font Awesome -->
    <!--<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">-->
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>

    <!-- Start your project here-->
    <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark special-color">

            <!-- Navbar brand -->

            <a class="navbar-brand" href="#" style = "font-family: 'Yatra One'; font-size: 150%;">votecrypt</a>
        
            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="basicExampleNav">
        
            <!-- Links -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    {% if request.user.username %}
                    <a class="nav-link" href="{% url 'node:auth_home' %}">Home
                    {% else %}
                    <a class="nav-link" href="#">Home
                    {% endif %}
                    <span class="sr-only">(current)</span>
                </a>
                </li>
        
            </ul>
            <!-- Links -->
        
            </div>
            <!-- Collapsible content -->
        
        </nav>
        <!--/.Navbar-->

        {% block messages %}
        {% if messages %}
        <div class="alert alert-success" role = "alert">
            {% for m in messages %}
            <li style="word-wrap: break-word;">{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</li>
            {% endfor %}
        </div>
        {% endif %}
        {% endblock %}
        

        {% block body %}
        {% endblock %}

        
    
    <!-- /Start your project here-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
</body>

</html>

voting/templates/blindtovalidate.html
{% extends 'base.html' %}

{% block body %}

<div class = "container" style = "padding-top: 3.5%;">    
    <div class = "col-md-3"></div>
    <div class = "col-md-6 text-center">
        <div class="card">
            <h3 class="card-header special-color white-text">Voter Validation Step - 1</h3>
            <div class="card-body">
                <!--<h4 class="card-title">Blind Signat</h4>-->
                <p class="card-text">Enter the secret message string and secret number.</p>

                <form method="post" action = "">
                    {% csrf_token %}
                    {% include 'form-template.html' %}  
                    
                    <button type="submit" class="btn btn-primary btn-lg">Submit</button>

                </form>
            </div>
        </div>
    </div>
    <div class = "col-md-3"></div>
</div>

{% endblock %}

voting/templates/form-template.html
{% for field in form %}
                    
    <div class = "md-form form-lg">        
        {{ field }}
        {{ field.label_tag }}
        <span class="text-danger small">{{ field.errors }}
        <div class="help-block small">{{ field.help_text }}</div>
    </div>


{% endfor %}

voting/templates/home.html
{% extends 'base.html' %}

{% block body %}

<div class = "container" style = "padding-top: 3.5%;">    
    <div class = "text-center">
        <div class="card">
            <h3 class="card-header special-color white-text">GET STARTED</h3>
            <div class="card-body">
                <h4 class="card-title">{{ tip_message }}</h4>
                {% if enter_poll %}
                <a href = "{% url 'verify_login' %}"><button type="button" class="btn btn-primary btn-lg">Enter Poll</button></a>
                {% elif hide_validate %}
                <a href = "{% url 'unblind_signed' %}"><button type="button" class="btn btn-primary btn-lg">Generate Unblinded Key</button></a>
                
                {% elif disable_validate %}
                <a href = "#"><button type="button" class="btn btn-disabled btn-lg">Validate</button></a>
                {% else %}
                <a href = "{% url 'blind_to_validate' %}"><button type="button" class="btn btn-primary btn-lg">Validate</button></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

voting/templates/login.html
{% extends 'base.html' %}

{% block body %}
<div class = "container" style = "padding-top: 3.5%;">    
    <div class = "col-md-3"></div>
    <div class = "col-md-6 text-center">
        <div class="card">
            <h3 class="card-header special-color white-text">Authority Login</h3>
            <div class="card-body">
                <!--<h4 class="card-title">Blind Signat</h4>-->

                <form method="post" action = "">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class = "md-form form-lg">
                        <span class="text-danger small">{{ field.errors }}
                        {{ field }}
                        {{ field.label_tag }}
                        <div class="help-block small">{{ field.help_text }}</div>
                    </div> 
                    {% endfor %}
                    
                    <button type="submit" class="btn btn-primary btn-lg">Submit</button>

                </form>
            </div>
        </div>
    </div>
    <div class = "col-md-3"></div>
</div>

{% endblock %}

voting/templates/new_question.html
{% extends 'base.html' %}

{% block body %}

<div class = "container" style = "padding-top: 3.5%;">    
    <div class = "col-md-3"></div>
    <div class = "col-md-6 text-center">
        <div class="card">
            <h3 class="card-header special-color white-text">Create New Poll</h3>
            <div class="card-body">
                
                <p class="card-head"></p>

                <form method="post" action = "">
                    {% csrf_token %}
                    {% include 'form-template.html' %}  
                    
                    <a href = "{% url 'poll:add_option' %}"><button type="button" class="btn btn-primary btn-lg">Add Option</button></a>
                    <button type="submit" class="btn btn-primary btn-lg">Publish</button>

                </form>
            </div>
        </div>
    </div>
    <div class = "col-md-3"></div>
</div>


{% endblock %}

voting/templates/new_validations.html
{% extends 'base.html' %}

{% block body %}

<div class="container" style = "padding-top: 4%;">
    <div class="card">
        <h3 class="card-header special-color white-text text-center">New Validation Requests</h3>
        <div class="card-body">            
        {% if blinded_secrets|length_is:'0' %}
            <h1>No new requests</h1>
        {% else %}
        <table class="table table-hover table-responsive">
            <thead class="primary-color text-center">
            <tr>
                <th scope="col" class = "white-text"><h5>#</h5></th>
                <th scope="col"class = "white-text"><h5>Blinded Secret</h5></th>
                <th scope="col"class = "white-text"><h5>Sign</h5></th>
            </tr>
            </thead>
            <tbody>
           {% for secret in blinded_secrets %}            
            <tr style="word-wrap:break-word;">
                <th scope="row">{{ forloop.counter }}</th>
                <td style="word-wrap:break-word; min-width: 895px; max-width: 895px;">{{ secret.hashed_blinded_secret }}</td>
                <td><a href = "{% url 'node:sign_blinded' secret.hashed_blinded_secret %}"><button type="button" class="btn btn-primary">Sign</button></a></td>
            </tr>            
            {% endfor %}
            </tbody>
        </table>
        {% endif %}
        </div>
        </div>
</div>

{% endblock %}

voting/templates/poll_detail.html
{% extends 'base.html' %}

{% block body %}

<div class = "container" style = "padding-top: 3.5%;">    
    <!--<div class = "col-md-3"></div>-->
    <div class = "row">
    <div class = "col-md-6">
        <div class="card">
            <h3 class="card-header special-color white-text">{{ question }}</h3>
            <div class="card-body">
                
                <p class="card-head"></p>

                <form method="post" action = "">
                    {% csrf_token %}
                    
                        {% for option in form %}   
                        
                            <!--<input type="radio" name="options" id="option1" autocomplete="off" checked> Radio 1 (preselected)-->
                            {% for choice in option %}
                            
                            {{ choice.tag }}   
                            <label for = "{{ choice.id_for_label }}" class="btn btn-primary {% if request.user.username or inactive %} disabled {% endif %}">{{ choice.choice_label }}
                                 
                            </label>     
                            <br>
                            {% endfor %}
                        
                        
                        {% endfor %}
                    
                    <br>

                    {% if inactive %} 
                    <div style = "padding-left: 35%;"><a href = "#"><button type="button" class="btn btn-primary btn-lg disabled">Voting Closed</button></a></div> 
                    {% elif request.user.username %}  
                    <div style = "padding-left: 35%;"><a href = "{% url 'poll:end_poll' poll_id %}"><button type="button" class="btn btn-primary btn-lg">End Poll</button></a></div>
                    
                    {% else %}
                    <div style = "padding-left: 35%;"><button type="submit" class="btn btn-primary btn-lg">Submit</button></div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
    <div class = "col-md-3"></div>
    <div class = "col-md-3">
        <div class="card">
            <h3 class="card-header special-color white-text">Current Results</h3>
            <div class="list-group">
            {% for option in poll_options %}
            <a href="#" class = "list-group-item waves-effect">{{ option.option }} - {{ option.count }} votes.</a>
            {% endfor %}
            </div>
        </div>            
    </div>
</div>
</div>


{% endblock %}

voting/templates/questions_list.html
{% extends 'base.html' %}

{% block body %}

{% if already_voted %}
<div class="alert alert-danger" role = "alert">    
    <li style="word-wrap: break-word;">>Vote Already Registered !</li>
</div>
{% endif %}

<div class="container" style = "padding-top: 4%;">
    <div class="card">
        <h3 class="card-header special-color white-text text-center">Select Poll to Enter</h3>
        <div class="card-body">
        <div class="list-group">
        <a href="#" class="list-group-item waves-effect active">Active Polls</a>
        {% for question in active_questions %}
        <a href="{% url 'poll:poll_detail' question.id %}" class="list-group-item waves-effect">{{ question.id }} - {{ question.question }}</a>

        {% endfor %}
        <a href="#" class="list-group-item waves-effect"></a>
        <a href="#" class="list-group-item waves-effect active">Closed Polls</a>
        
        {% for question in inactive_questions %}
        <a href="{% url 'poll:poll_detail' question.id %}" class="list-group-item waves-effect">{{ question.id }} - {{ question.question }}</a>

        {% endfor %}

        </div>
        </div>
        </div>
</div>

{% endblock %}

voting/templates/signedtounblind.html
{% extends 'base.html' %}

{% block body %}

<div class = "container" style = "padding-top: 3.5%;">    
    <div class = "col-md-3"></div>
    <div class = "col-md-6 text-center">
        <div class="card">
            <h3 class="card-header special-color white-text">Voter Validation Step - 2</h3>
            <div class="card-body">
                <!--<h4 class="card-title">Blind Signat</h4>-->
                <p class="card-text">Enter the secret number to generate the unblinded string.</p>

                <form method="post" action = "">
                    {% csrf_token %}
                    {% include 'form-template.html' %}  
                    
                    <button type="submit" class="btn btn-primary btn-lg">Submit</button>

                </form>
            </div>
        </div>
    </div>
    <div class = "col-md-3"></div>
</div>

{% endblock %}

voting/templates/verify_login.html
{% extends 'base.html' %}



{% block body %}
<div class = "container" style = "padding-top: 3.5%;">    
    <div class = "col-md-3"></div>
    <div class = "col-md-6 text-center">
        <div class="card">
            <h3 class="card-header special-color white-text">Voter Validation Step - 3</h3>
            <div class="card-body">
                <!--<h4 class="card-title">Blind Signat</h4>-->
                <p class="card-text">Enter the secretID to verify signature and enter the Poll.</p>

                <form method="post" action = "">
                    {% csrf_token %}
                    {% include 'form-template.html' %}  
                    
                    <button type="submit" class="btn btn-primary btn-lg">Submit</button>

                </form>
            </div>
        </div>
    </div>
    <div class = "col-md-3"></div>
</div>



{% endblock %}